version: "3.9"
services:
  postgres:
    hostname: postgres
    image: postgres:16.2
    environment:
      POSTGRES_DB: "restful"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      GDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres: