apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    isDefault: false
    basicAuth: false
    uid: loki
    jsonData:
      maxLines: 100
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: \[.+,(.+?),
          name: TraceID
          url: $${__value.raw}
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:9411
    editable: false
    isDefault: true
    basicAuth: false
    version: 1
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLog:
        datasourceUid: 'loki'
